server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ecommerce?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

#application:
#  security:
#    jwt:
#      secret-key: B3pSB4hhA4ApRtJQVv/FXoKwsCKZtNQ3CM81G0sPS0tQ+eLsW+6W/EZwE2oEahQK
#      expiration: 86400000  # 1 ng?y
#      refresh-token:
#        expiration: 604800000  # 7 ng?y
